namespace Presentation.BtnLlamadas
{
    partial class FormLlamada
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.BtnRegistrar = new System.Windows.Forms.Button();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.TxtObservacion = new System.Windows.Forms.TextBox();
            this.TxtProblema = new System.Windows.Forms.TextBox();
            this.TxtDescripcion = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.CbxCompañero = new System.Windows.Forms.ComboBox();
            this.TxtRef = new System.Windows.Forms.TextBox();
            this.LblTituloMostrar = new System.Windows.Forms.Label();
            this.TxtUsuario = new System.Windows.Forms.TextBox();
            this.DgvRegistro = new System.Windows.Forms.DataGridView();
            this.tableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.DgvRegistro)).BeginInit();
            this.SuspendLayout();
            // 
            // BtnRegistrar
            // 
            this.BtnRegistrar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.BtnRegistrar.BackColor = System.Drawing.Color.SteelBlue;
            this.BtnRegistrar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnRegistrar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.BtnRegistrar.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnRegistrar.ForeColor = System.Drawing.Color.White;
            this.BtnRegistrar.Location = new System.Drawing.Point(305, 237);
            this.BtnRegistrar.Name = "BtnRegistrar";
            this.BtnRegistrar.Size = new System.Drawing.Size(280, 32);
            this.BtnRegistrar.TabIndex = 13;
            this.BtnRegistrar.Text = "Registrar Llamada";
            this.BtnRegistrar.UseVisualStyleBackColor = false;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.tableLayoutPanel1.CellBorderStyle = System.Windows.Forms.TableLayoutPanelCellBorderStyle.Single;
            this.tableLayoutPanel1.ColumnCount = 6;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48.07018F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 51.92982F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 79F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 182F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 192F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 172F));
            this.tableLayoutPanel1.Controls.Add(this.TxtUsuario, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.TxtObservacion, 5, 1);
            this.tableLayoutPanel1.Controls.Add(this.TxtProblema, 4, 1);
            this.tableLayoutPanel1.Controls.Add(this.TxtDescripcion, 3, 1);
            this.tableLayoutPanel1.Controls.Add(this.label1, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.label2, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.label3, 2, 0);
            this.tableLayoutPanel1.Controls.Add(this.label4, 3, 0);
            this.tableLayoutPanel1.Controls.Add(this.label5, 4, 0);
            this.tableLayoutPanel1.Controls.Add(this.label6, 5, 0);
            this.tableLayoutPanel1.Controls.Add(this.CbxCompañero, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.TxtRef, 2, 1);
            this.tableLayoutPanel1.Location = new System.Drawing.Point(12, 77);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 2;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 39.81482F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60.18518F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(897, 139);
            this.tableLayoutPanel1.TabIndex = 12;
            // 
            // TxtObservacion
            // 
            this.TxtObservacion.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.TxtObservacion.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(12)))), ((int)(((byte)(28)))));
            this.TxtObservacion.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.TxtObservacion.ForeColor = System.Drawing.Color.White;
            this.TxtObservacion.Location = new System.Drawing.Point(727, 61);
            this.TxtObservacion.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.TxtObservacion.MaxLength = 160;
            this.TxtObservacion.Multiline = true;
            this.TxtObservacion.Name = "TxtObservacion";
            this.TxtObservacion.Size = new System.Drawing.Size(165, 72);
            this.TxtObservacion.TabIndex = 22;
            this.TxtObservacion.Text = "El otro día no podía correr por la playa debido a que estuve concentrado en poder" +
    " irme a correr por el paraíso llamado Urá.";
            // 
            // TxtProblema
            // 
            this.TxtProblema.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.TxtProblema.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(12)))), ((int)(((byte)(28)))));
            this.TxtProblema.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.TxtProblema.ForeColor = System.Drawing.Color.White;
            this.TxtProblema.Location = new System.Drawing.Point(534, 61);
            this.TxtProblema.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.TxtProblema.MaxLength = 160;
            this.TxtProblema.Multiline = true;
            this.TxtProblema.Name = "TxtProblema";
            this.TxtProblema.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.TxtProblema.Size = new System.Drawing.Size(184, 72);
            this.TxtProblema.TabIndex = 21;
            this.TxtProblema.Text = "El otro día no podía correr por la playa debido a que estuve concentrado en poder" +
    " irme a correr por el paraíso llamado Urá.";
            // 
            // TxtDescripcion
            // 
            this.TxtDescripcion.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.TxtDescripcion.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(12)))), ((int)(((byte)(28)))));
            this.TxtDescripcion.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.TxtDescripcion.Cursor = System.Windows.Forms.Cursors.Arrow;
            this.TxtDescripcion.ForeColor = System.Drawing.Color.White;
            this.TxtDescripcion.Location = new System.Drawing.Point(351, 74);
            this.TxtDescripcion.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.TxtDescripcion.MaxLength = 50;
            this.TxtDescripcion.Multiline = true;
            this.TxtDescripcion.Name = "TxtDescripcion";
            this.TxtDescripcion.Size = new System.Drawing.Size(174, 46);
            this.TxtDescripcion.TabIndex = 20;
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label1.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(24, 12);
            this.label1.Margin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(80, 36);
            this.label1.TabIndex = 1;
            this.label1.Text = "Quien pasa la llamada?";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label2
            // 
            this.label2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label2.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(157, 12);
            this.label2.Margin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(80, 36);
            this.label2.TabIndex = 2;
            this.label2.Text = "Quien atiende?";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label3.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(271, 12);
            this.label3.Margin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(70, 36);
            this.label3.TabIndex = 3;
            this.label3.Text = "Referencia";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label4
            // 
            this.label4.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label4.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(398, 12);
            this.label4.Margin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(80, 36);
            this.label4.TabIndex = 4;
            this.label4.Text = "Descripción";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label5
            // 
            this.label5.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label5.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(576, 12);
            this.label5.Margin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(99, 36);
            this.label5.TabIndex = 5;
            this.label5.Text = "Problema";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label6
            // 
            this.label6.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label6.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(752, 12);
            this.label6.Margin = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(114, 36);
            this.label6.TabIndex = 6;
            this.label6.Text = "Observación";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // CbxCompañero
            // 
            this.CbxCompañero.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.CbxCompañero.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(12)))), ((int)(((byte)(28)))));
            this.CbxCompañero.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.CbxCompañero.ForeColor = System.Drawing.Color.White;
            this.CbxCompañero.FormattingEnabled = true;
            this.CbxCompañero.Items.AddRange(new object[] {
            "Alegría-Dulantzi",
            "Amurrio",
            "Añana",
            "Aramaio",
            "Armiñón",
            "Arraia-Maeztu",
            "Arrazua-Ubarrundia",
            "Artziniega",
            "Asparrena",
            "Ayala/Aiara",
            "Baños de Ebro/Mañueta",
            "Barrundia",
            "Berantevilla",
            "Bernedo",
            "Campezo/Kanpezu",
            "Elburgo/Burgelu",
            "Elciego",
            "Elvillar/Bilar",
            "Erriberagoitia/Ribera Alta",
            "Harana/Valle de Arana",
            "Iruña Oka/Iruña de Oca",
            "Iruraiz-Gauna",
            "Kripan",
            "Kuartango",
            "Labastida/Bastida",
            "Lagrán",
            "Laguardia",
            "Lanciego/Lantziego",
            "Lantarón",
            "Lapuebla de Labarca",
            "Laudio/Llodio",
            "Legutio",
            "Leza",
            "Moreda de Álava",
            "Navaridas",
            "Okondo",
            "Oyón-Oion",
            "Peñacerrada-Urizaharra",
            "Ribera Baja/Erribera Beitia",
            "Salvatierra/Agurain",
            "Samaniego",
            "San Millán/Donemiliaga",
            "Urkabustaiz",
            "Valdegovía/Gaubea",
            "Villabuena de Álava/Eskuernaga",
            "Vitoria-Gasteiz",
            "Yécora/Iekora",
            "Zalduondo",
            "Zambrana",
            "Zigoitia",
            "Zuia",
            "Abengibre",
            "Alatoz",
            "Albacete",
            "Albatana",
            "Alborea",
            "Alcadozo",
            "Alcalá del Júcar",
            "Alcaraz",
            "Almansa",
            "Alpera",
            "Ayna",
            "Balazote",
            "Ballestero, El",
            "Balsa de Ves",
            "Barrax",
            "Bienservida",
            "Bogarra",
            "Bonete",
            "Bonillo, El",
            "Carcelén",
            "Casas de Juan Núñez",
            "Casas de Lázaro",
            "Casas de Ves",
            "Casas-Ibáñez",
            "Caudete",
            "Cenizate",
            "Chinchilla de Monte-Aragón",
            "Corral-Rubio",
            "Cotillas",
            "Elche de la Sierra",
            "Férez",
            "Fuensanta",
            "Fuente-Álamo",
            "Fuentealbilla",
            "Gineta, La",
            "Golosalvo",
            "Hellín",
            "Herrera, La",
            "Higueruela",
            "Hoya-Gonzalo",
            "Jorquera",
            "Letur",
            "Lezuza",
            "Liétor",
            "Madrigueras",
            "Mahora",
            "Masegoso",
            "Minaya",
            "Molinicos",
            "Montalvos",
            "Montealegre del Castillo",
            "Motilleja",
            "Munera",
            "Navas de Jorquera",
            "Nerpio",
            "Ontur",
            "Ossa de Montiel",
            "Paterna del Madera",
            "Peñas de San Pedro",
            "Peñascosa",
            "Pétrola",
            "Povedilla",
            "Pozo Cañada",
            "Pozohondo",
            "Pozo-Lorente",
            "Pozuelo",
            "Recueja, La",
            "Riópar",
            "Robledo",
            "Roda, La",
            "Salobre",
            "San Pedro",
            "Socovos",
            "Tarazona de la Mancha",
            "Tobarra",
            "Valdeganga",
            "Vianos",
            "Villa de Ves",
            "Villalgordo del Júcar",
            "Villamalea",
            "Villapalacios",
            "Villarrobledo",
            "Villatoya",
            "Villavaliente",
            "Villaverde de Guadalimar",
            "Viveros",
            "Yeste",
            "Adsubia",
            "Agost",
            "Agres",
            "Aigües",
            "Albatera",
            "Alcalalí",
            "Alcocer de Planes",
            "Alcoleja",
            "Alcoy/Alcoi",
            "Alfafara",
            "Alfàs del Pi, l\'",
            "Algorfa",
            "Algueña",
            "Alicante/Alacant",
            "Almoradí",
            "Almudaina",
            "Alqueria d\'Asnar, l\'",
            "Altea",
            "Aspe",
            "Balones",
            "Banyeres de Mariola",
            "Benasau",
            "Beneixama",
            "Benejúzar",
            "Benferri",
            "Beniarbeig",
            "Beniardá",
            "Beniarrés",
            "Benidoleig",
            "Benidorm",
            "Benifallim",
            "Benifato",
            "Benigembla",
            "Benijófar",
            "Benilloba",
            "Benillup",
            "Benimantell",
            "Benimarfull",
            "Benimassot",
            "Benimeli",
            "Benissa",
            "Benitachell/Poble Nou de Benitatxell, el",
            "Biar",
            "Bigastro",
            "Bolulla",
            "Busot",
            "Callosa de Segura",
            "Callosa d\'En Sarrià",
            "Calp",
            "Campello, el",
            "Campo de Mirra/Camp de Mirra, el",
            "Cañada",
            "Castalla",
            "Castell de Castells",
            "Castell de Guadalest, el",
            "Catral",
            "Cocentaina",
            "Confrides",
            "Cox",
            "Crevillent",
            "Daya Nueva",
            "Daya Vieja",
            "Dénia",
            "Dolores",
            "Elche/Elx",
            "Elda",
            "Facheca",
            "Famorca",
            "Finestrat",
            "Fondó de les Neus, el/Hondón de las Nieves",
            "Formentera del Segura",
            "Gaianes",
            "Gata de Gorgos",
            "Gorga",
            "Granja de Rocamora",
            "Guardamar del Segura",
            "Hondón de los Frailes",
            "Ibi",
            "Jacarilla",
            "Jávea/Xàbia",
            "Jijona/Xixona",
            "Llíber",
            "Lorcha/Orxa, l\'",
            "Millena",
            "Monforte del Cid",
            "Monóvar/Monòver",
            "Montesinos, Los",
            "Murla",
            "Muro de Alcoy",
            "Mutxamel",
            "Novelda",
            "Nucia, la",
            "Ondara",
            "Onil",
            "Orba",
            "Orihuela",
            "Orxeta",
            "Parcent",
            "Pedreguer",
            "Pego",
            "Penàguila",
            "Petrer",
            "Pilar de la Horadada",
            "Pinós, el/Pinoso",
            "Planes",
            "Poblets, els",
            "Polop",
            "Quatretondeta",
            "Rafal",
            "Ràfol d\'Almúnia, el",
            "Redován",
            "Relleu",
            "Rojales",
            "Romana, la",
            "Sagra",
            "Salinas",
            "San Fulgencio",
            "San Isidro",
            "San Miguel de Salinas",
            "San Vicente del Raspeig/Sant Vicent del Raspeig",
            "Sanet y Negrals",
            "Sant Joan d\'Alacant",
            "Santa Pola",
            "Sax",
            "Sella",
            "Senija",
            "Tàrbena",
            "Teulada",
            "Tibi",
            "Tollos",
            "Tormos",
            "Torremanzanas/Torre de les Maçanes, la",
            "Torrevieja",
            "Vall d\'Alcalà, la",
            "Vall de Gallinera",
            "Vall de Laguar, la",
            "Vall d\'Ebo, la",
            "Verger, el",
            "Villajoyosa/Vila Joiosa, la",
            "Villena",
            "Xaló",
            "Abla",
            "Abrucena",
            "Adra",
            "Albánchez",
            "Alboloduy",
            "Albox",
            "Alcolea",
            "Alcóntar",
            "Alcudia de Monteagud",
            "Alhabia",
            "Alhama de Almería",
            "Alicún",
            "Almería",
            "Almócita",
            "Alsodux",
            "Antas",
            "Arboleas",
            "Armuña de Almanzora",
            "Bacares",
            "Bayárcal",
            "Bayarque",
            "Bédar",
            "Beires",
            "Benahadux",
            "Benitagla",
            "Benizalón",
            "Bentarique",
            "Berja",
            "Canjáyar",
            "Cantoria",
            "Carboneras",
            "Castro de Filabres",
            "Chercos",
            "Chirivel",
            "Cóbdar",
            "Cuevas del Almanzora",
            "Dalías",
            "Ejido, El",
            "Enix",
            "Felix",
            "Fines",
            "Fiñana",
            "Fondón",
            "Gádor",
            "Gallardos, Los",
            "Garrucha",
            "Gérgal",
            "Huécija",
            "Huércal de Almería",
            "Huércal-Overa",
            "Illar",
            "Instinción",
            "Laroya",
            "Láujar de Andarax",
            "Líjar",
            "Lubrín",
            "Lucainena de las Torres",
            "Lúcar",
            "Macael",
            "María",
            "Mojácar",
            "Mojonera, La",
            "Nacimiento",
            "Níjar",
            "Ohanes",
            "Olula de Castro",
            "Olula del Río",
            "Oria",
            "Padules",
            "Partaloa",
            "Paterna del Río",
            "Pechina",
            "Pulpí",
            "Purchena",
            "Rágol",
            "Rioja",
            "Roquetas de Mar",
            "Santa Cruz de Marchena",
            "Santa Fe de Mondújar",
            "Senés",
            "Serón",
            "Sierro",
            "Somontín",
            "Sorbas",
            "Suflí",
            "Tabernas",
            "Taberno",
            "Tahal",
            "Terque",
            "Tíjola",
            "Tres Villas, Las",
            "Turre",
            "Turrillas",
            "Uleila del Campo",
            "Urrácal",
            "Velefique",
            "Vélez-Blanco",
            "Vélez-Rubio",
            "Vera",
            "Viator",
            "Vícar",
            "Zurgena",
            "Adanero",
            "Adrada, La",
            "Albornos",
            "Aldeanueva de Santa Cruz",
            "Aldeaseca",
            "Aldehuela, La",
            "Amavida",
            "Arenal, El",
            "Arenas de San Pedro",
            "Arevalillo",
            "Arévalo",
            "Aveinte",
            "Avellaneda",
            "Ávila",
            "Barco de Ávila, El",
            "Barraco, El",
            "Barromán",
            "Becedas",
            "Becedillas",
            "Bercial de Zapardiel",
            "Berlanas, Las",
            "Bernuy-Zapardiel",
            "Berrocalejo de Aragona",
            "Blascomillán",
            "Blasconuño de Matacabras",
            "Blascosancho",
            "Bohodón, El",
            "Bohoyo",
            "Bonilla de la Sierra",
            "Brabos",
            "Bularros",
            "Burgohondo",
            "Cabezas de Alambre",
            "Cabezas del Pozo",
            "Cabezas del Villar",
            "Cabizuela",
            "Canales",
            "Candeleda",
            "Cantiveros",
            "Cardeñosa",
            "Carrera, La",
            "Casas del Puerto",
            "Casasola",
            "Casavieja",
            "Casillas",
            "Castellanos de Zapardiel",
            "Cebreros",
            "Cepeda la Mora",
            "Chamartín",
            "Cillán",
            "Cisla",
            "Colilla, La",
            "Collado de Contreras",
            "Collado del Mirón",
            "Constanzana",
            "Crespos",
            "Cuevas del Valle",
            "Diego del Carpio",
            "Donjimeno",
            "Donvidas",
            "Espinosa de los Caballeros",
            "Flores de Ávila",
            "Fontiveros",
            "Fresnedilla",
            "Fresno, El",
            "Fuente el Saúz",
            "Fuentes de Año",
            "Gallegos de Altamiros",
            "Gallegos de Sobrinos",
            "Garganta del Villar",
            "Gavilanes",
            "Gemuño",
            "Gil García",
            "Gilbuena",
            "Gimialcón",
            "Gotarrendura",
            "Grandes y San Martín",
            "Guisando",
            "Gutierre-Muñoz",
            "Hernansancho",
            "Herradón de Pinares",
            "Herreros de Suso",
            "Higuera de las Dueñas",
            "Hija de Dios, La",
            "Horcajada, La",
            "Horcajo de las Torres",
            "Hornillo, El",
            "Hoyo de Pinares, El",
            "Hoyocasero",
            "Hoyorredondo",
            "Hoyos de Miguel Muñoz",
            "Hoyos del Collado",
            "Hoyos del Espino",
            "Hurtumpascual",
            "Junciana",
            "Langa",
            "Lanzahíta",
            "Llanos de Tormes, Los",
            "Losar del Barco, El",
            "Madrigal de las Altas Torres",
            "Maello",
            "Malpartida de Corneja",
            "Mamblas",
            "Mancera de Arriba",
            "Manjabálago",
            "Marlín",
            "Martiherrero",
            "Martínez",
            "Mediana de Voltoya",
            "Medinilla",
            "Mengamuñoz",
            "Mesegar de Corneja",
            "Mijares",
            "Mingorría",
            "Mirón, El",
            "Mironcillo",
            "Mirueña de los Infanzones",
            "Mombeltrán",
            "Monsalupe",
            "Moraleja de Matacabras",
            "Muñana",
            "Muñico",
            "Muñogalindo",
            "Muñogrande",
            "Muñomer del Peco",
            "Muñopepe",
            "Muñosancho",
            "Muñotello",
            "Narrillos del Álamo",
            "Narrillos del Rebollar",
            "Narros de Saldueña",
            "Narros del Castillo",
            "Narros del Puerto",
            "Nava de Arévalo",
            "Nava del Barco",
            "Navacepedilla de Corneja",
            "Navadijos",
            "Navaescurial",
            "Navahondilla",
            "Navalacruz",
            "Navalmoral",
            "Navalonguilla",
            "Navalosa",
            "Navalperal de Pinares",
            "Navalperal de Tormes",
            "Navaluenga",
            "Navaquesera",
            "Navarredonda de Gredos",
            "Navarredondilla",
            "Navarrevisca",
            "Navas del Marqués, Las",
            "Navatalgordo",
            "Navatejares",
            "Neila de San Miguel",
            "Niharra",
            "Ojos-Albos",
            "Orbita",
            "Oso, El",
            "Padiernos",
            "Pajares de Adaja",
            "Palacios de Goda",
            "Papatrigo",
            "Parral, El",
            "Pascualcobo",
            "Pedro Bernardo",
            "Pedro-Rodríguez",
            "Peguerinos",
            "Peñalba de Ávila",
            "Piedrahíta",
            "Piedralaves",
            "Poveda",
            "Poyales del Hoyo",
            "Pozanco",
            "Pradosegar",
            "Puerto Castilla",
            "Rasueros",
            "Riocabado",
            "Riofrío",
            "Rivilla de Barajas",
            "Salobral",
            "Salvadiós",
            "San Bartolomé de Béjar",
            "San Bartolomé de Corneja",
            "San Bartolomé de Pinares",
            "San Esteban de los Patos",
            "San Esteban de Zapardiel",
            "San Esteban del Valle",
            "San García de Ingelmos",
            "San Juan de Gredos",
            "San Juan de la Encinilla",
            "San Juan de la Nava",
            "San Juan del Molinillo",
            "San Juan del Olmo",
            "San Lorenzo de Tormes",
            "San Martín de la Vega del Alberche",
            "San Martín del Pimpollar",
            "San Miguel de Corneja",
            "San Miguel de Serrezuela",
            "San Pascual",
            "San Pedro del Arroyo",
            "San Vicente de Arévalo",
            "Sanchidrián",
            "Sanchorreja",
            "Santa Cruz de Pinares",
            "Santa Cruz del Valle",
            "Santa María de los Caballeros",
            "Santa María del Arroyo",
            "Santa María del Berrocal",
            "Santa María del Cubillo",
            "Santa María del Tiétar",
            "Santiago del Collado",
            "Santiago del Tormes",
            "Santo Domingo de las Posadas",
            "Santo Tomé de Zabarcos",
            "Serrada, La",
            "Serranillos",
            "Sigeres",
            "Sinlabajos",
            "Solana de Ávila",
            "Solana de Rioalmar",
            "Solosancho",
            "Sotalbo",
            "Sotillo de la Adrada",
            "Tiemblo, El",
            "Tiñosillos",
            "Tolbaños",
            "Tormellas",
            "Tornadizos de Ávila",
            "Torre, La",
            "Tórtoles",
            "Umbrías",
            "Vadillo de la Sierra",
            "Valdecasa",
            "Vega de Santa María",
            "Velayos",
            "Villaflor",
            "Villafranca de la Sierra",
            "Villanueva de Ávila",
            "Villanueva de Gómez",
            "Villanueva del Aceral",
            "Villanueva del Campillo",
            "Villar de Corneja",
            "Villarejo del Valle",
            "Villatoro",
            "Viñegra de Moraña",
            "Vita",
            "Zapardiel de la Cañada",
            "Zapardiel de la Ribera",
            "Acedera",
            "Aceuchal",
            "Ahillones",
            "Alange",
            "Albuera, La",
            "Alburquerque",
            "Alconchel",
            "Alconera",
            "Aljucén",
            "Almendral",
            "Almendralejo",
            "Arroyo de San Serván",
            "Atalaya",
            "Azuaga",
            "Badajoz",
            "Barcarrota",
            "Baterno",
            "Benquerencia de la Serena",
            "Berlanga",
            "Bienvenida",
            "Bodonal de la Sierra",
            "Burguillos del Cerro",
            "Cabeza del Buey",
            "Cabeza la Vaca",
            "Calamonte",
            "Calera de León",
            "Calzadilla de los Barros",
            "Campanario",
            "Campillo de Llerena",
            "Capilla",
            "Carmonita",
            "Carrascalejo, El",
            "Casas de Don Pedro",
            "Casas de Reina",
            "Castilblanco",
            "Castuera",
            "Cheles",
            "Codosera, La",
            "Cordobilla de Lácara",
            "Coronada, La",
            "Corte de Peleas",
            "Cristina",
            "Don Álvaro",
            "Don Benito",
            "Entrín Bajo",
            "Esparragalejo",
            "Esparragosa de la Serena",
            "Esparragosa de Lares",
            "Feria",
            "Fregenal de la Sierra",
            "Fuenlabrada de los Montes",
            "Fuente de Cantos",
            "Fuente del Arco",
            "Fuente del Maestre",
            "Fuentes de León",
            "Garbayuela",
            "Garlitos",
            "Garrovilla, La",
            "Granja de Torrehermosa",
            "Guareña",
            "Haba, La",
            "Helechosa de los Montes",
            "Herrera del Duque",
            "Higuera de la Serena",
            "Higuera de Llerena",
            "Higuera de Vargas",
            "Higuera la Real",
            "Hinojosa del Valle",
            "Hornachos",
            "Jerez de los Caballeros",
            "Lapa, La",
            "Llera",
            "Llerena",
            "Lobón",
            "Magacela",
            "Maguilla",
            "Malcocinado",
            "Malpartida de la Serena",
            "Manchita",
            "Medellín",
            "Medina de las Torres",
            "Mengabril",
            "Mérida",
            "Mirandilla",
            "Monesterio",
            "Montemolín",
            "Monterrubio de la Serena",
            "Montijo",
            "Morera, La",
            "Nava de Santiago, La",
            "Navalvillar de Pela",
            "Nogales",
            "Oliva de la Frontera",
            "Oliva de Mérida",
            "Olivenza",
            "Orellana de la Sierra",
            "Orellana la Vieja",
            "Palomas",
            "Parra, La",
            "Peñalsordo",
            "Peraleda del Zaucejo",
            "Puebla de Alcocer",
            "Puebla de la Calzada",
            "Puebla de la Reina",
            "Puebla de Obando",
            "Puebla de Sancho Pérez",
            "Puebla del Maestre",
            "Puebla del Prior",
            "Pueblonuevo del Guadiana",
            "Quintana de la Serena",
            "Reina",
            "Rena",
            "Retamal de Llerena",
            "Ribera del Fresno",
            "Risco",
            "Roca de la Sierra, La",
            "Salvaleón",
            "Salvatierra de los Barros",
            "San Pedro de Mérida",
            "San Vicente de Alcántara",
            "Sancti-Spíritus",
            "Santa Amalia",
            "Santa Marta",
            "Santos de Maimona, Los",
            "Segura de León",
            "Siruela",
            "Solana de los Barros",
            "Talarrubias",
            "Talavera la Real",
            "Táliga",
            "Tamurejo",
            "Torre de Miguel Sesmero",
            "Torremayor",
            "Torremejía",
            "Trasierra",
            "Trujillanos",
            "Usagre",
            "Valdecaballeros",
            "Valdelacalzada",
            "Valdetorres",
            "Valencia de las Torres",
            "Valencia del Mombuey",
            "Valencia del Ventoso",
            "Valle de la Serena",
            "Valle de Matamoros",
            "Valle de Santa Ana",
            "Valverde de Burguillos",
            "Valverde de Leganés",
            "Valverde de Llerena",
            "Valverde de Mérida",
            "Villafranca de los Barros",
            "Villagarcía de la Torre",
            "Villagonzalo",
            "Villalba de los Barros",
            "Villanueva de la Serena",
            "Villanueva del Fresno",
            "Villar de Rena",
            "Villar del Rey",
            "Villarta de los Montes",
            "Zafra",
            "Zahínos",
            "Zalamea de la Serena",
            "Zarza, La",
            "Zarza-Capilla",
            "Alaior",
            "Alaró",
            "Alcúdia",
            "Algaida",
            "Andratx",
            "Ariany",
            "Artà",
            "Banyalbufar",
            "Binissalem",
            "Búger",
            "Bunyola",
            "Calvià",
            "Campanet",
            "Campos",
            "Capdepera",
            "Castell, Es",
            "Ciutadella de Menorca",
            "Consell",
            "Costitx",
            "Deyá",
            "Eivissa",
            "Escorca",
            "Esporles",
            "Estellencs",
            "Felanitx",
            "Ferreries",
            "Formentera",
            "Fornalutx",
            "Inca",
            "Lloret de Vistalegre",
            "Lloseta",
            "Llubí",
            "Llucmajor",
            "Manacor",
            "Mancor de la Vall",
            "Maó",
            "Maria de la Salut",
            "Marratxí",
            "Mercadal, Es",
            "Migjorn Gran, Es",
            "Montuïri",
            "Muro",
            "Palma",
            "Petra",
            "Pobla, Sa",
            "Pollença",
            "Porreres",
            "Puigpunyent",
            "Salines, Ses",
            "Sant Antoni de Portmany",
            "Sant Joan",
            "Sant Joan de Labritja",
            "Sant Josep de sa Talaia",
            "Sant Llorenç des Cardassar",
            "Sant Lluís",
            "Santa Eugènia",
            "Santa Eulalia del Río",
            "Santa Margalida",
            "Santa María del Camí",
            "Santanyí",
            "Selva",
            "Sencelles",
            "Sineu",
            "Sóller",
            "Son Servera",
            "Valldemossa",
            "Vilafranca de Bonany",
            "Abrera",
            "Aguilar de Segarra",
            "Aiguafreda",
            "Alella",
            "Alpens",
            "Ametlla del Vallès, L\'",
            "Arenys de Mar",
            "Arenys de Munt",
            "Argençola",
            "Argentona",
            "Artés",
            "Avià",
            "Avinyó",
            "Avinyonet del Penedès",
            "Badalona",
            "Badia del Vallès",
            "Bagà",
            "Balenyà",
            "Balsareny",
            "Barberà del Vallès",
            "Barcelona",
            "Begues",
            "Bellprat",
            "Berga",
            "Bigues i Riells",
            "Borredà",
            "Bruc, El",
            "Brull, El",
            "Cabanyes, Les",
            "Cabrera d\'Anoia",
            "Cabrera de Mar",
            "Cabrils",
            "Calaf",
            "Calders",
            "Caldes de Montbui",
            "Caldes d\'Estrac",
            "Calella",
            "Calldetenes",
            "Callús",
            "Calonge de Segarra",
            "Campins",
            "Canet de Mar",
            "Canovelles",
            "Cànoves i Samalús",
            "Canyelles",
            "Capellades",
            "Capolat",
            "Cardedeu",
            "Cardona",
            "Carme",
            "Casserres",
            "Castell de l\'Areny",
            "Castellar de n\'Hug",
            "Castellar del Riu",
            "Castellar del Vallès",
            "Castellbell i el Vilar",
            "Castellbisbal",
            "Castellcir",
            "Castelldefels",
            "Castellet i la Gornal",
            "Castellfollit de Riubregós",
            "Castellfollit del Boix",
            "Castellgalí",
            "Castellnou de Bages",
            "Castellolí",
            "Castellterçol",
            "Castellví de la Marca",
            "Castellví de Rosanes",
            "Centelles",
            "Cercs",
            "Cerdanyola del Vallès",
            "Cervelló",
            "Collbató",
            "Collsuspina",
            "Copons",
            "Corbera de Llobregat",
            "Cornellà de Llobregat",
            "Cubelles",
            "Dosrius",
            "Esparreguera",
            "Esplugues de Llobregat",
            "Espunyola, L\'",
            "Estany, L\'",
            "Figaró-Montmany",
            "Fígols",
            "Fogars de la Selva",
            "Fogars de Montclús",
            "Folgueroles",
            "Fonollosa",
            "Font-rubí",
            "Franqueses del Vallès, Les",
            "Gaià",
            "Gallifa",
            "Garriga, La",
            "Gavà",
            "Gelida",
            "Gironella",
            "Gisclareny",
            "Granada, La",
            "Granera",
            "Granollers",
            "Gualba",
            "Guardiola de Berguedà",
            "Gurb",
            "Hospitalet de Llobregat, L\'",
            "Hostalets de Pierola, Els",
            "Igualada",
            "Jorba",
            "Llacuna, La",
            "Llagosta, La",
            "Lliçà d\'Amunt",
            "Lliçà de Vall",
            "Llinars del Vallès",
            "Lluçà",
            "Malgrat de Mar",
            "Malla",
            "Manlleu",
            "Manresa",
            "Marganell",
            "Martorell",
            "Martorelles",
            "Masies de Roda, Les",
            "Masies de Voltregà, Les",
            "Masnou, El",
            "Masquefa",
            "Matadepera",
            "Mataró",
            "Mediona",
            "Moià",
            "Molins de Rei",
            "Mollet del Vallès",
            "Monistrol de Calders",
            "Monistrol de Montserrat",
            "Montcada i Reixac",
            "Montclar",
            "Montesquiu",
            "Montgat",
            "Montmajor",
            "Montmaneu",
            "Montmeló",
            "Montornès del Vallès",
            "Montseny",
            "Muntanyola",
            "Mura",
            "Navarcles",
            "Navàs",
            "Nou de Berguedà, La",
            "Òdena",
            "Olèrdola",
            "Olesa de Bonesvalls",
            "Olesa de Montserrat",
            "Olivella",
            "Olost",
            "Olvan",
            "Orís",
            "Oristà",
            "Orpí",
            "Òrrius",
            "Pacs del Penedès",
            "Palafolls",
            "Palau-solità i Plegamans",
            "Pallejà",
            "Palma de Cervelló, La",
            "Papiol, El",
            "Parets del Vallès",
            "Perafita",
            "Piera",
            "Pineda de Mar",
            "Pla del Penedès, El",
            "Pobla de Claramunt, La",
            "Pobla de Lillet, La",
            "Polinyà",
            "Pont de Vilomara i Rocafort, El",
            "Pontons",
            "Prat de Llobregat, El",
            "Prats de Lluçanès",
            "Prats de Rei, Els",
            "Premià de Dalt",
            "Premià de Mar",
            "Puigdàlber",
            "Puig-reig",
            "Pujalt",
            "Quar, La",
            "Rajadell",
            "Rellinars",
            "Ripollet",
            "Roca del Vallès, La",
            "Roda de Ter",
            "Rubí",
            "Rubió",
            "Rupit i Pruit",
            "Sabadell",
            "Sagàs",
            "Saldes",
            "Sallent",
            "Sant Adrià de Besòs",
            "Sant Agustí de Lluçanès",
            "Sant Andreu de la Barca",
            "Sant Andreu de Llavaneres",
            "Sant Antoni de Vilamajor",
            "Sant Bartomeu del Grau",
            "Sant Boi de Llobregat",
            "Sant Boi de Lluçanès",
            "Sant Cebrià de Vallalta",
            "Sant Celoni",
            "Sant Climent de Llobregat",
            "Sant Cugat del Vallès",
            "Sant Cugat Sesgarrigues",
            "Sant Esteve de Palautordera",
            "Sant Esteve Sesrovires",
            "Sant Feliu de Codines",
            "Sant Feliu de Llobregat",
            "Sant Feliu Sasserra",
            "Sant Fost de Campsentelles",
            "Sant Fruitós de Bages",
            "Sant Hipòlit de Voltregà",
            "Sant Iscle de Vallalta",
            "Sant Jaume de Frontanyà",
            "Sant Joan de Vilatorrada",
            "Sant Joan Despí",
            "Sant Julià de Cerdanyola",
            "Sant Julià de Vilatorta",
            "Sant Just Desvern",
            "Sant Llorenç d\'Hortons",
            "Sant Llorenç Savall",
            "Sant Martí d\'Albars",
            "Sant Martí de Centelles",
            "Sant Martí de Tous",
            "Sant Martí Sarroca",
            "Sant Martí Sesgueioles",
            "Sant Mateu de Bages",
            "Sant Pere de Ribes",
            "Sant Pere de Riudebitlles",
            "Sant Pere de Torelló",
            "Sant Pere de Vilamajor",
            "Sant Pere Sallavinera",
            "Sant Pol de Mar",
            "Sant Quintí de Mediona",
            "Sant Quirze de Besora",
            "Sant Quirze del Vallès",
            "Sant Quirze Safaja",
            "Sant Sadurní d\'Anoia",
            "Sant Sadurní d\'Osormort",
            "Sant Salvador de Guardiola",
            "Sant Vicenç de Castellet",
            "Sant Vicenç de Montalt",
            "Sant Vicenç de Torelló",
            "Sant Vicenç dels Horts",
            "Santa Cecília de Voltregà",
            "Santa Coloma de Cervelló",
            "Santa Coloma de Gramenet",
            "Santa Eugènia de Berga",
            "Santa Eulàlia de Riuprimer",
            "Santa Eulàlia de Ronçana",
            "Santa Fe del Penedès",
            "Santa Margarida de Montbui",
            "Santa Margarida i els Monjos",
            "Santa Maria de Besora",
            "Santa Maria de Corcó",
            "Santa Maria de Martorelles",
            "Santa Maria de Merlès",
            "Santa Maria de Miralles",
            "Santa Maria de Palautordera",
            "Santa Maria d\'Oló",
            "Santa Perpètua de Mogoda",
            "Santa Susanna",
            "Santpedor",
            "Sentmenat",
            "Seva",
            "Sitges",
            "Sobremunt",
            "Sora",
            "Subirats",
            "Súria",
            "Tagamanent",
            "Talamanca",
            "Taradell",
            "Tavèrnoles",
            "Tavertet",
            "Teià",
            "Terrassa",
            "Tiana",
            "Tona",
            "Tordera",
            "Torelló",
            "Torre de Claramunt, La",
            "Torrelavit",
            "Torrelles de Foix",
            "Torrelles de Llobregat",
            "Ullastrell",
            "Vacarisses",
            "Vallbona d\'Anoia",
            "Vallcebre",
            "Vallgorguina",
            "Vallirana",
            "Vallromanes",
            "Veciana",
            "Vic",
            "Vilada",
            "Viladecans",
            "Viladecavalls",
            "Vilafranca del Penedès",
            "Vilalba Sasserra",
            "Vilanova de Sau",
            "Vilanova del Camí",
            "Vilanova del Vallès",
            "Vilanova i la Geltrú",
            "Vilassar de Dalt",
            "Vilassar de Mar",
            "Vilobí del Penedès",
            "Viver i Serrateix",
            "Abajas",
            "Adrada de Haza",
            "Aguas Cándidas",
            "Aguilar de Bureba",
            "Albillos",
            "Alcocero de Mola",
            "Alfoz de Bricia",
            "Alfoz de Quintanadueñas",
            "Alfoz de Santa Gadea",
            "Altable",
            "Altos, Los",
            "Ameyugo",
            "Anguix",
            "Aranda de Duero",
            "Arandilla",
            "Arauzo de Miel",
            "Arauzo de Salce",
            "Arauzo de Torre",
            "Arcos",
            "Arenillas de Riopisuerga",
            "Arija",
            "Arlanzón",
            "Arraya de Oca",
            "Atapuerca",
            "Ausines, Los",
            "Avellanosa de Muñó",
            "Bahabón de Esgueva",
            "Balbases, Los",
            "Baños de Valdearados",
            "Bañuelos de Bureba",
            "Barbadillo de Herreros",
            "Barbadillo del Mercado",
            "Barbadillo del Pez",
            "Barrio de Muñó",
            "Barrios de Bureba, Los",
            "Barrios de Colina",
            "Basconcillos del Tozo",
            "Bascuñana",
            "Belbimbre",
            "Belorado",
            "Berberana",
            "Berlangas de Roa",
            "Berzosa de Bureba",
            "Bozoó",
            "Brazacorta",
            "Briviesca",
            "Bugedo",
            "Buniel",
            "Burgos",
            "Busto de Bureba",
            "Cabañes de Esgueva",
            "Cabezón de la Sierra",
            "Caleruega",
            "Campillo de Aranda",
            "Campolara",
            "Canicosa de la Sierra",
            "Cantabrana",
            "Carazo",
            "Carcedo de Bureba",
            "Carcedo de Burgos",
            "Cardeñadijo",
            "Cardeñajimeno",
            "Cardeñuela Riopico",
            "Carrias",
            "Cascajares de Bureba",
            "Cascajares de la Sierra",
            "Castellanos de Castro",
            "Castil de Peones",
            "Castildelgado",
            "Castrillo de la Reina",
            "Castrillo de la Vega",
            "Castrillo de Riopisuerga",
            "Castrillo del Val",
            "Castrillo Matajudíos",
            "Castrojeriz",
            "Cavia",
            "Cayuela",
            "Cebrecos",
            "Celada del Camino",
            "Cerezo de Río Tirón",
            "Cerratón de Juarros",
            "Ciadoncha",
            "Cillaperlata",
            "Cilleruelo de Abajo",
            "Cilleruelo de Arriba",
            "Ciruelos de Cervera",
            "Cogollos",
            "Condado de Treviño",
            "Contreras",
            "Coruña del Conde",
            "Covarrubias",
            "Cubillo del Campo",
            "Cubo de Bureba",
            "Cueva de Roa, La",
            "Cuevas de San Clemente",
            "Encío",
            "Espinosa de Cervera",
            "Espinosa de los Monteros",
            "Espinosa del Camino",
            "Estépar",
            "Fontioso",
            "Frandovínez",
            "Fresneda de la Sierra Tirón",
            "Fresneña",
            "Fresnillo de las Dueñas",
            "Fresno de Río Tirón",
            "Fresno de Rodilla",
            "Frías",
            "Fuentebureba",
            "Fuentecén",
            "Fuentelcésped",
            "Fuentelisendo",
            "Fuentemolinos",
            "Fuentenebro",
            "Fuentespina",
            "Galbarros",
            "Gallega, La",
            "Grijalba",
            "Grisaleña",
            "Gumiel de Izán",
            "Gumiel de Mercado",
            "Hacinas",
            "Haza",
            "Hontanas",
            "Hontangas",
            "Hontoria de la Cantera",
            "Hontoria de Valdearados",
            "Hontoria del Pinar",
            "Hormazas, Las",
            "Hornillos del Camino",
            "Horra, La",
            "Hortigüela",
            "Hoyales de Roa",
            "Huérmeces",
            "Huerta de Arriba",
            "Huerta de Rey",
            "Humada",
            "Hurones",
            "Ibeas de Juarros",
            "Ibrillos",
            "Iglesiarrubia",
            "Iglesias",
            "Isar",
            "Itero del Castillo",
            "Jaramillo de la Fuente",
            "Jaramillo Quemado",
            "Junta de Traslaloma",
            "Junta de Villalba de Losa",
            "Jurisdicción de Lara",
            "Jurisdicción de San Zadornil",
            "Lerma",
            "Llano de Bureba",
            "Madrigal del Monte",
            "Madrigalejo del Monte",
            "Mahamud",
            "Mambrilla de Castrejón",
            "Mambrillas de Lara",
            "Mamolar",
            "Manciles",
            "Mazuela",
            "Mecerreyes",
            "Medina de Pomar",
            "Melgar de Fernamental",
            "Merindad de Cuesta-Urria",
            "Merindad de Montija",
            "Merindad de Río Ubierna",
            "Merindad de Sotoscueva",
            "Merindad de Valdeporres",
            "Merindad de Valdivielso",
            "Milagros",
            "Miranda de Ebro",
            "Miraveche",
            "Modúbar de la Emparedada",
            "Monasterio de la Sierra",
            "Monasterio de Rodilla",
            "Moncalvillo",
            "Monterrubio de la Demanda",
            "Montorio",
            "Moradillo de Roa",
            "Nava de Roa",
            "Navas de Bureba",
            "Nebreda",
            "Neila",
            "Olmedillo de Roa",
            "Olmillos de Muñó",
            "Oña",
            "Oquillas",
            "Orbaneja Riopico",
            "Padilla de Abajo",
            "Padilla de Arriba",
            "Padrones de Bureba",
            "Palacios de la Sierra",
            "Palacios de Riopisuerga",
            "Palazuelos de la Sierra",
            "Palazuelos de Muñó",
            "Pampliega",
            "Pancorbo",
            "Pardilla",
            "Partido de la Sierra en Tobalina",
            "Pedrosa de Duero",
            "Pedrosa de Río Úrbel",
            "Pedrosa del Páramo",
            "Pedrosa del Príncipe",
            "Peñaranda de Duero",
            "Peral de Arlanza",
            "Piérnigas",
            "Pineda de la Sierra",
            "Pineda Trasmonte",
            "Pinilla de los Barruecos",
            "Pinilla de los Moros",
            "Pinilla Trasmonte",
            "Poza de la Sal",
            "Prádanos de Bureba",
            "Pradoluengo",
            "Presencio",
            "Puebla de Arganzón, La",
            "Puentedura",
            "Quemada",
            "Quintana del Pidio",
            "Quintanabureba",
            "Quintanaélez",
            "Quintanaortuño",
            "Quintanapalla",
            "Quintanar de la Sierra",
            "Quintanavides",
            "Quintanilla de la Mata",
            "Quintanilla del Agua y Tordueles",
            "Quintanilla del Coco",
            "Quintanilla San García",
            "Quintanilla Vivar",
            "Quintanillas, Las",
            "Rabanera del Pinar",
            "Rábanos",
            "Rabé de las Calzadas",
            "Rebolledo de la Torre",
            "Redecilla del Camino",
            "Redecilla del Campo",
            "Regumiel de la Sierra",
            "Reinoso",
            "Retuerta",
            "Revilla del Campo",
            "Revilla Vallejera",
            "Revilla y Ahedo, La",
            "Revillarruz",
            "Rezmondo",
            "Riocavado de la Sierra",
            "Roa",
            "Rojas",
            "Royuela de Río Franco",
            "Rubena",
            "Rublacedo de Abajo",
            "Rucandio",
            "Salas de Bureba",
            "Salas de los Infantes",
            "Saldaña de Burgos",
            "Salinillas de Bureba",
            "San Adrián de Juarros",
            "San Juan del Monte",
            "San Mamés de Burgos",
            "San Martín de Rubiales",
            "San Millán de Lara",
            "San Vicente del Valle",
            "Santa Cecilia",
            "Santa Cruz de la Salceda",
            "Santa Cruz del Valle Urbión",
            "Santa Gadea del Cid",
            "Santa Inés",
            "Santa María del Campo",
            "Santa María del Invierno",
            "Santa María del Mercadillo",
            "Santa María Rivarredonda",
            "Santa Olalla de Bureba",
            "Santibáñez de Esgueva",
            "Santibáñez del Val",
            "Santo Domingo de Silos",
            "Sargentes de la Lora",
            "Sarracín",
            "Sasamón",
            "Sequera de Haza, La",
            "Solarana",
            "Sordillos",
            "Sotillo de la Ribera",
            "Sotragero",
            "Sotresgudo",
            "Susinos del Páramo",
            "Tamarón",
            "Tardajos",
            "Tejada",
            "Terradillos de Esgueva",
            "Tinieblas de la Sierra",
            "Tobar",
            "Tordómar",
            "Torrecilla del Monte",
            "Torregalindo",
            "Torrelara",
            "Torrepadre",
            "Torresandino",
            "Tórtoles de Esgueva",
            "Tosantos",
            "Trespaderne",
            "Tubilla del Agua",
            "Tubilla del Lago",
            "Úrbel del Castillo",
            "Vadocondes",
            "Valdeande",
            "Valdezate",
            "Valdorros",
            "Vallarta de Bureba",
            "Valle de las Navas",
            "Valle de Losa",
            "Valle de Manzanedo",
            "Valle de Mena",
            "Valle de Oca",
            "Valle de Santibáñez",
            "Valle de Sedano",
            "Valle de Tobalina",
            "Valle de Valdebezana",
            "Valle de Valdelaguna",
            "Valle de Valdelucio",
            "Valle de Zamanzas",
            "Vallejera",
            "Valles de Palenzuela",
            "Valluércanes",
            "Valmala",
            "Vid de Bureba, La",
            "Vid y Barrios, La",
            "Vileña",
            "Villadiego",
            "Villaescusa de Roa",
            "Villaescusa la Sombría",
            "Villaespasa",
            "Villafranca Montes de Oca",
            "Villafruela",
            "Villagalijo",
            "Villagonzalo Pedernales",
            "Villahoz",
            "Villalba de Duero",
            "Villalbilla de Burgos",
            "Villalbilla de Gumiel",
            "Villaldemiro",
            "Villalmanzo",
            "Villamayor de los Montes",
            "Villamayor de Treviño",
            "Villambistia",
            "Villamedianilla",
            "Villamiel de la Sierra",
            "Villangómez",
            "Villanueva de Argaño",
            "Villanueva de Carazo",
            "Villanueva de Gumiel",
            "Villanueva de Teba",
            "Villaquirán de la Puebla",
            "Villaquirán de los Infantes",
            "Villarcayo de Merindad de Castilla la Vieja",
            "Villariezo",
            "Villasandino",
            "Villasur de Herreros",
            "Villatuelda",
            "Villaverde del Monte",
            "Villaverde-Mogina",
            "Villayerno Morquillas",
            "Villazopeque",
            "Villegas",
            "Villoruebo",
            "Viloria de Rioja",
            "Vilviestre del Pinar",
            "Vizcaínos",
            "Zael",
            "Zarzosa de Río Pisuerga",
            "Zazuar",
            "Zuñeda",
            "Abadía",
            "Abertura",
            "Acebo",
            "Acehúche",
            "Aceituna",
            "Ahigal",
            "Alagón del Río",
            "Albalá",
            "Alcántara",
            "Alcollarín",
            "Alcuéscar",
            "Aldea del Cano",
            "Aldea del Obispo, La",
            "Aldeacentenera",
            "Aldeanueva de la Vera",
            "Aldeanueva del Camino",
            "Aldehuela de Jerte",
            "Alía",
            "Aliseda",
            "Almaraz",
            "Almoharín",
            "Arroyo de la Luz",
            "Arroyomolinos",
            "Arroyomolinos de la Vera",
            "Baños de Montemayor",
            "Barrado",
            "Belvís de Monroy",
            "Benquerencia",
            "Berrocalejo",
            "Berzocana",
            "Bohonal de Ibor",
            "Botija",
            "Brozas",
            "Cabañas del Castillo",
            "Cabezabellosa",
            "Cabezuela del Valle",
            "Cabrero",
            "Cáceres",
            "Cachorrilla",
            "Cadalso",
            "Calzadilla",
            "Caminomorisco",
            "Campillo de Deleitosa",
            "Campo Lugar",
            "Cañamero",
            "Cañaveral",
            "Carbajo",
            "Carcaboso",
            "Carrascalejo",
            "Casar de Cáceres",
            "Casar de Palomero",
            "Casares de las Hurdes",
            "Casas de Don Antonio",
            "Casas de Don Gómez",
            "Casas de Millán",
            "Casas de Miravete",
            "Casas del Castañar",
            "Casas del Monte",
            "Casatejada",
            "Casillas de Coria",
            "Castañar de Ibor",
            "Ceclavín",
            "Cedillo",
            "Cerezo",
            "Cilleros",
            "Collado",
            "Conquista de la Sierra",
            "Coria",
            "Cuacos de Yuste",
            "Cumbre, La",
            "Deleitosa",
            "Descargamaría",
            "Eljas",
            "Escurial",
            "Fresnedoso de Ibor",
            "Galisteo",
            "Garciaz",
            "Garganta, La",
            "Garganta la Olla",
            "Gargantilla",
            "Gargüera",
            "Garrovillas de Alconétar",
            "Garvín",
            "Gata",
            "Gordo, El",
            "Granja, La",
            "Guadalupe",
            "Guijo de Coria",
            "Guijo de Galisteo",
            "Guijo de Granadilla",
            "Guijo de Santa Bárbara",
            "Herguijuela",
            "Hernán-Pérez",
            "Herrera de Alcántara",
            "Herreruela",
            "Hervás",
            "Higuera",
            "Hinojal",
            "Holguera",
            "Hoyos",
            "Huélaga",
            "Ibahernando",
            "Jaraicejo",
            "Jaraíz de la Vera",
            "Jarandilla de la Vera",
            "Jarilla",
            "Jerte",
            "Ladrillar",
            "Logrosán",
            "Losar de la Vera",
            "Madrigal de la Vera",
            "Madrigalejo",
            "Madroñera",
            "Majadas",
            "Malpartida de Cáceres",
            "Malpartida de Plasencia",
            "Marchagaz",
            "Mata de Alcántara",
            "Membrío",
            "Mesas de Ibor",
            "Miajadas",
            "Millanes",
            "Mirabel",
            "Mohedas de Granadilla",
            "Monroy",
            "Montánchez",
            "Montehermoso",
            "Moraleja",
            "Morcillo",
            "Navaconcejo",
            "Navalmoral de la Mata",
            "Navalvillar de Ibor",
            "Navas del Madroño",
            "Navezuelas",
            "Nuñomoral",
            "Oliva de Plasencia",
            "Palomero",
            "Pasarón de la Vera",
            "Pedroso de Acim",
            "Peraleda de la Mata",
            "Peraleda de San Román",
            "Perales del Puerto",
            "Pescueza",
            "Pesga, La",
            "Piedras Albas",
            "Pinofranqueado",
            "Piornal",
            "Plasencia",
            "Plasenzuela",
            "Portaje",
            "Portezuelo",
            "Pozuelo de Zarzón",
            "Puerto de Santa Cruz",
            "Rebollar",
            "Riolobos",
            "Robledillo de Gata",
            "Robledillo de la Vera",
            "Robledillo de Trujillo",
            "Robledollano",
            "Romangordo",
            "Rosalejo",
            "Ruanes",
            "Salorino",
            "Salvatierra de Santiago",
            "San Martín de Trevejo",
            "Santa Ana",
            "Santa Cruz de la Sierra",
            "Santa Cruz de Paniagua",
            "Santa Marta de Magasca",
            "Santiago de Alcántara",
            "Santiago del Campo",
            "Santibáñez el Alto",
            "Santibáñez el Bajo",
            "Saucedilla",
            "Segura de Toro",
            "Serradilla",
            "Serrejón",
            "Sierra de Fuentes",
            "Talaván",
            "Talaveruela de la Vera",
            "Talayuela",
            "Tejeda de Tiétar",
            "Toril",
            "Tornavacas",
            "Torno, El",
            "Torre de Don Miguel",
            "Torre de Santa María",
            "Torrecilla de los Ángeles",
            "Torrecillas de la Tiesa",
            "Torrejón el Rubio",
            "Torrejoncillo",
            "Torremenga",
            "Torremocha",
            "Torreorgaz",
            "Torrequemada",
            "Trujillo",
            "Valdastillas",
            "Valdecañas de Tajo",
            "Valdefuentes",
            "Valdehúncar",
            "Valdelacasa de Tajo",
            "Valdemorales",
            "Valdeobispo",
            "Valencia de Alcántara",
            "Valverde de la Vera",
            "Valverde del Fresno",
            "Vegaviana",
            "Viandar de la Vera",
            "Villa del Campo",
            "Villa del Rey",
            "Villamesías",
            "Villamiel",
            "Villanueva de la Sierra",
            "Villanueva de la Vera",
            "Villar de Plasencia",
            "Villar del Pedroso",
            "Villasbuenas de Gata",
            "Zarza de Granadilla",
            "Zarza de Montánchez",
            "Zarza la Mayor",
            "Zorita",
            "Alcalá de los Gazules",
            "Alcalá del Valle",
            "Algar",
            "Algeciras",
            "Algodonales",
            "Arcos de la Frontera",
            "Barbate",
            "Barrios, Los",
            "Benalup-Casas Viejas",
            "Benaocaz",
            "Bornos",
            "Bosque, El",
            "Cádiz",
            "Castellar de la Frontera",
            "Chiclana de la Frontera",
            "Chipiona",
            "Conil de la Frontera",
            "Espera",
            "Gastor, El",
            "Grazalema",
            "Jerez de la Frontera",
            "Jimena de la Frontera",
            "Línea de la Concepción, La",
            "Medina-Sidonia",
            "Olvera",
            "Paterna de Rivera",
            "Prado del Rey",
            "Puerto de Santa María, El",
            "Puerto Real",
            "Puerto Serrano",
            "Rota",
            "San Fernando",
            "San José del Valle",
            "San Roque",
            "Sanlúcar de Barrameda",
            "Setenil de las Bodegas",
            "Tarifa",
            "Torre Alháquime",
            "Trebujena",
            "Ubrique",
            "Vejer de la Frontera",
            "Villaluenga del Rosario",
            "Villamartín",
            "Zahara",
            "Aín",
            "Albocàsser",
            "Alcalà de Xivert",
            "Alcora, l\'",
            "Alcudia de Veo",
            "Alfondeguilla",
            "Algimia de Almonacid",
            "Almazora/Almassora",
            "Almedíjar",
            "Almenara",
            "Alquerías del Niño Perdido",
            "Altura",
            "Arañuel",
            "Ares del Maestrat",
            "Argelita",
            "Artana",
            "Atzeneta del Maestrat",
            "Ayódar",
            "Azuébar",
            "Barracas",
            "Bejís",
            "Benafer",
            "Benafigos",
            "Benasal",
            "Benicarló",
            "Benicasim/Benicàssim",
            "Benlloch",
            "Betxí",
            "Borriana/Burriana",
            "Borriol",
            "Cabanes",
            "Càlig",
            "Canet lo Roig",
            "Castell de Cabres",
            "Castellfort",
            "Castellnovo",
            "Castellón de la Plana/Castelló de la Plana",
            "Castillo de Villamalefa",
            "Catí",
            "Caudiel",
            "Cervera del Maestre",
            "Chert/Xert",
            "Chilches/Xilxes",
            "Chodos/Xodos",
            "Chóvar",
            "Cinctorres",
            "Cirat",
            "Cortes de Arenoso",
            "Costur",
            "Coves de Vinromà, les",
            "Culla",
            "Eslida",
            "Espadilla",
            "Fanzara",
            "Figueroles",
            "Forcall",
            "Fuente la Reina",
            "Fuentes de Ayódar",
            "Gaibiel",
            "Geldo",
            "Herbés",
            "Higueras",
            "Jana, la",
            "Jérica",
            "Llosa, la",
            "Lucena del Cid",
            "Ludiente",
            "Mata de Morella, la",
            "Matet",
            "Moncofa",
            "Montán",
            "Montanejos",
            "Morella",
            "Navajas",
            "Nules",
            "Olocau del Rey",
            "Onda",
            "Oropesa del Mar/Orpesa",
            "Palanques",
            "Pavías",
            "Peníscola/Peñíscola",
            "Pina de Montalgrao",
            "Pobla de Benifassà, la",
            "Pobla Tornesa, la",
            "Portell de Morella",
            "Puebla de Arenoso",
            "Ribesalbes",
            "Rossell",
            "Sacañet",
            "Salzadella, la",
            "San Rafael del Río",
            "Sant Joan de Moró",
            "Sant Jordi/San Jorge",
            "Sant Mateu",
            "Santa Magdalena de Pulpis",
            "Sarratella",
            "Segorbe",
            "Sierra Engarcerán",
            "Soneja",
            "Sot de Ferrer",
            "Sueras/Suera",
            "Tales",
            "Teresa",
            "Tírig",
            "Todolella",
            "Toga",
            "Torás",
            "Toro, El",
            "Torralba del Pinar",
            "Torre d\'En Besora, la",
            "Torre d\'en Doménec, la",
            "Torreblanca",
            "Torrechiva",
            "Traiguera",
            "Useras/Useres, les",
            "Vall d\'Alba",
            "Vall de Almonacid",
            "Vall d\'Uixó, la",
            "Vallat",
            "Vallibona",
            "Vilafamés",
            "Vilanova d\'Alcolea",
            "Vilar de Canes",
            "Vila-real",
            "Vilavella, la",
            "Villafranca del Cid/Vilafranca",
            "Villahermosa del Río",
            "Villamalur",
            "Villanueva de Viver",
            "Villores",
            "Vinaròs",
            "Vistabella del Maestrazgo",
            "Viver",
            "Zorita del Maestrazgo",
            "Zucaina",
            "Abenójar",
            "Agudo",
            "Alamillo",
            "Albaladejo",
            "Alcázar de San Juan",
            "Alcoba",
            "Alcolea de Calatrava",
            "Alcubillas",
            "Aldea del Rey",
            "Alhambra",
            "Almadén",
            "Almadenejos",
            "Almagro",
            "Almedina",
            "Almodóvar del Campo",
            "Almuradiel",
            "Anchuras",
            "Arenales de San Gregorio",
            "Arenas de San Juan",
            "Argamasilla de Alba",
            "Argamasilla de Calatrava",
            "Arroba de los Montes",
            "Ballesteros de Calatrava",
            "Bolaños de Calatrava",
            "Brazatortas",
            "Cabezarados",
            "Cabezarrubias del Puerto",
            "Calzada de Calatrava",
            "Campo de Criptana",
            "Cañada de Calatrava",
            "Caracuel de Calatrava",
            "Carrión de Calatrava",
            "Carrizosa",
            "Castellar de Santiago",
            "Chillón",
            "Ciudad Real",
            "Corral de Calatrava",
            "Cortijos, Los",
            "Cózar",
            "Daimiel",
            "Fernán Caballero",
            "Fontanarejo",
            "Fuencaliente",
            "Fuenllana",
            "Fuente el Fresno",
            "Granátula de Calatrava",
            "Guadalmez",
            "Herencia",
            "Hinojosas de Calatrava",
            "Horcajo de los Montes",
            "Labores, Las",
            "Llanos del Caudillo",
            "Luciana",
            "Malagón",
            "Manzanares",
            "Membrilla",
            "Mestanza",
            "Miguelturra",
            "Montiel",
            "Moral de Calatrava",
            "Navalpino",
            "Navas de Estena",
            "Pedro Muñoz",
            "Picón",
            "Piedrabuena",
            "Poblete",
            "Porzuna",
            "Pozuelo de Calatrava",
            "Pozuelos de Calatrava, Los",
            "Puebla de Don Rodrigo",
            "Puebla del Príncipe",
            "Puerto Lápice",
            "Puertollano",
            "Retuerta del Bullaque",
            "Robledo, El",
            "Ruidera",
            "Saceruela",
            "San Carlos del Valle",
            "San Lorenzo de Calatrava",
            "Santa Cruz de los Cáñamos",
            "Santa Cruz de Mudela",
            "Socuéllamos",
            "Solana, La",
            "Solana del Pino",
            "Terrinches",
            "Tomelloso",
            "Torralba de Calatrava",
            "Torre de Juan Abad",
            "Torrenueva",
            "Valdemanco del Esteras",
            "Valdepeñas",
            "Valenzuela de Calatrava",
            "Villahermosa",
            "Villamanrique",
            "Villamayor de Calatrava",
            "Villanueva de la Fuente",
            "Villanueva de los Infantes",
            "Villanueva de San Carlos",
            "Villar del Pozo",
            "Villarrubia de los Ojos",
            "Villarta de San Juan",
            "Viso del Marqués",
            "Adamuz",
            "Aguilar de la Frontera",
            "Alcaracejos",
            "Almedinilla",
            "Almodóvar del Río",
            "Añora",
            "Baena",
            "Belalcázar",
            "Belmez",
            "Benamejí",
            "Blázquez, Los",
            "Bujalance",
            "Cabra",
            "Cañete de las Torres",
            "Carcabuey",
            "Cardeña",
            "Carlota, La",
            "Carpio, El",
            "Castro del Río",
            "Conquista",
            "Córdoba",
            "Doña Mencía",
            "Dos Torres",
            "Encinas Reales",
            "Espejo",
            "Espiel",
            "Fernán-Núñez",
            "Fuente la Lancha",
            "Fuente Obejuna",
            "Fuente Palmera",
            "Fuente-Tójar",
            "Granjuela, La",
            "Guadalcázar",
            "Guijo, El",
            "Hinojosa del Duque",
            "Hornachuelos",
            "Iznájar",
            "Lucena",
            "Luque",
            "Montalbán de Córdoba",
            "Montemayor",
            "Montilla",
            "Montoro",
            "Monturque",
            "Moriles",
            "Nueva Carteya",
            "Obejo",
            "Palenciana",
            "Palma del Río",
            "Pedro Abad",
            "Pedroche",
            "Peñarroya-Pueblonuevo",
            "Posadas",
            "Pozoblanco",
            "Priego de Córdoba",
            "Puente Genil",
            "Rambla, La",
            "Rute",
            "San Sebastián de los Ballesteros",
            "Santa Eufemia",
            "Santaella",
            "Torrecampo",
            "Valenzuela",
            "Valsequillo",
            "Victoria, La",
            "Villa del Río",
            "Villafranca de Córdoba",
            "Villaharta",
            "Villanueva de Córdoba",
            "Villanueva del Duque",
            "Villanueva del Rey",
            "Villaralto",
            "Villaviciosa de Córdoba",
            "Viso, El",
            "Zuheros",
            "Abegondo",
            "Ames",
            "Aranga",
            "Ares",
            "Arteixo",
            "Arzúa",
            "Baña, A",
            "Bergondo",
            "Betanzos",
            "Boimorto",
            "Boiro",
            "Boqueixón",
            "Brión",
            "Cabana de Bergantiños",
            "Cabanas",
            "Camariñas",
            "Cambre",
            "Capela, A",
            "Carballo",
            "Cariño",
            "Carnota",
            "Carral",
            "Cedeira",
            "Cee",
            "Cerceda",
            "Cerdido",
            "Cesuras",
            "Coirós",
            "Corcubión",
            "Coristanco",
            "Coruña, A",
            "Culleredo",
            "Curtis",
            "Dodro",
            "Dumbría",
            "Fene",
            "Ferrol",
            "Fisterra",
            "Frades",
            "Irixoa",
            "Laracha, A",
            "Laxe",
            "Lousame",
            "Malpica de Bergantiños",
            "Mañón",
            "Mazaricos",
            "Melide",
            "Mesía",
            "Miño",
            "Moeche",
            "Monfero",
            "Mugardos",
            "Muros",
            "Muxía",
            "Narón",
            "Neda",
            "Negreira",
            "Noia",
            "Oleiros",
            "Ordes",
            "Oroso",
            "Ortigueira",
            "Outes",
            "Oza dos Ríos",
            "Paderne",
            "Padrón",
            "Pino, O",
            "Pobra do Caramiñal, A",
            "Ponteceso",
            "Pontedeume",
            "Pontes de García Rodríguez, As",
            "Porto do Son",
            "Rianxo",
            "Ribeira",
            "Rois",
            "Sada",
            "San Sadurniño",
            "Santa Comba",
            "Santiago de Compostela",
            "Santiso",
            "Sobrado",
            "Somozas, As",
            "Teo",
            "Toques",
            "Tordoia",
            "Touro",
            "Trazo",
            "Val do Dubra",
            "Valdoviño",
            "Vedra"});
            this.CbxCompañero.Location = new System.Drawing.Point(4, 89);
            this.CbxCompañero.Margin = new System.Windows.Forms.Padding(3, 5, 3, 0);
            this.CbxCompañero.Name = "CbxCompañero";
            this.CbxCompañero.Size = new System.Drawing.Size(121, 21);
            this.CbxCompañero.TabIndex = 18;
            this.CbxCompañero.Text = "Carlos Quintero";
            // 
            // TxtRef
            // 
            this.TxtRef.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.TxtRef.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(12)))), ((int)(((byte)(28)))));
            this.TxtRef.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.TxtRef.Enabled = false;
            this.TxtRef.ForeColor = System.Drawing.Color.White;
            this.TxtRef.Location = new System.Drawing.Point(270, 89);
            this.TxtRef.Margin = new System.Windows.Forms.Padding(3, 5, 3, 0);
            this.TxtRef.Multiline = true;
            this.TxtRef.Name = "TxtRef";
            this.TxtRef.Size = new System.Drawing.Size(72, 20);
            this.TxtRef.TabIndex = 17;
            this.TxtRef.Text = "80000";
            this.TxtRef.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // LblTituloMostrar
            // 
            this.LblTituloMostrar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.LblTituloMostrar.AutoSize = true;
            this.LblTituloMostrar.BackColor = System.Drawing.Color.Transparent;
            this.LblTituloMostrar.Font = new System.Drawing.Font("Microsoft Tai Le", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblTituloMostrar.ForeColor = System.Drawing.Color.White;
            this.LblTituloMostrar.Location = new System.Drawing.Point(358, 28);
            this.LblTituloMostrar.Name = "LblTituloMostrar";
            this.LblTituloMostrar.Size = new System.Drawing.Size(178, 23);
            this.LblTituloMostrar.TabIndex = 11;
            this.LblTituloMostrar.Text = "Registro telefónico";
            // 
            // TxtUsuario
            // 
            this.TxtUsuario.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.TxtUsuario.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(12)))), ((int)(((byte)(28)))));
            this.TxtUsuario.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.TxtUsuario.Enabled = false;
            this.TxtUsuario.ForeColor = System.Drawing.Color.White;
            this.TxtUsuario.Location = new System.Drawing.Point(132, 89);
            this.TxtUsuario.Margin = new System.Windows.Forms.Padding(3, 5, 3, 0);
            this.TxtUsuario.Multiline = true;
            this.TxtUsuario.Name = "TxtUsuario";
            this.TxtUsuario.Size = new System.Drawing.Size(131, 20);
            this.TxtUsuario.TabIndex = 23;
            this.TxtUsuario.Text = "Carlos Quintero";
            this.TxtUsuario.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // DgvRegistro
            // 
            this.DgvRegistro.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.DgvRegistro.Location = new System.Drawing.Point(12, 345);
            this.DgvRegistro.Name = "DgvRegistro";
            this.DgvRegistro.Size = new System.Drawing.Size(897, 247);
            this.DgvRegistro.TabIndex = 14;
            // 
            // FormLlamada
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(12)))), ((int)(((byte)(28)))));
            this.ClientSize = new System.Drawing.Size(921, 620);
            this.Controls.Add(this.DgvRegistro);
            this.Controls.Add(this.BtnRegistrar);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Controls.Add(this.LblTituloMostrar);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormLlamada";
            this.Text = "FormLlamada";
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.DgvRegistro)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button BtnRegistrar;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TextBox TxtObservacion;
        private System.Windows.Forms.TextBox TxtProblema;
        private System.Windows.Forms.TextBox TxtDescripcion;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.ComboBox CbxCompañero;
        private System.Windows.Forms.TextBox TxtRef;
        private System.Windows.Forms.Label LblTituloMostrar;
        private System.Windows.Forms.TextBox TxtUsuario;
        private System.Windows.Forms.DataGridView DgvRegistro;
    }
}